trigger:
  branches:
    include:
      - releases/*

variables:
  - group: KamiYomu-Secrets

  - name: DOTNET_VERSION
    value: '8.0.x'
  - name: SOLUTION_PATH
    value: 'src/KamiYomu.CrawlerAgents.Sample.sln'
  - name: PROJECT_PATH
    value: 'src/KamiYomu.CrawlerAgents.Sample/KamiYomu.CrawlerAgents.Sample.csproj'
  - name: NUGET_CONFIG_PATH
    value: 'src/NuGet.config'

stages:
# ============================================================
# BUILD STAGE
# ============================================================
- stage: Build
  displayName: "Build, Test, Pack"
  jobs:
    - job: BuildJob
      pool:
        vmImage: ubuntu-latest

      steps:
        - checkout: self

        - task: UseDotNet@2
          displayName: "Setup .NET"
          inputs:
            packageType: sdk
            version: $(DOTNET_VERSION)

        # -----------------------------
        # Extract version
        # -----------------------------
        - bash: |
            BRANCH_NAME="${BUILD_SOURCEBRANCH#refs/heads/}"
            RAW_VERSION="${BRANCH_NAME#releases/}"

            if [[ "$RAW_VERSION" == *"-"* ]]; then
              VERSION_BASE="${RAW_VERSION%%-*}"
              VERSION_SUFFIX="${RAW_VERSION#*-}"
              IS_PRERELEASE=true
            else
              VERSION_BASE="$RAW_VERSION"
              VERSION_SUFFIX=""
              IS_PRERELEASE=false
            fi

            if [[ ! "$VERSION_BASE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid version: $VERSION_BASE"
              exit 1
            fi

            TAG="$VERSION_BASE"
            [[ -n "$VERSION_SUFFIX" ]] && TAG="$TAG-$VERSION_SUFFIX"

            echo "##vso[task.setvariable variable=VERSION]$VERSION_BASE"
            echo "##vso[task.setvariable variable=VERSION_SUFFIX]$VERSION_SUFFIX"
            echo "##vso[task.setvariable variable=IS_PRERELEASE]$IS_PRERELEASE"
            echo "##vso[task.setvariable variable=TAG]$TAG"
          displayName: "Extract version"

        # -----------------------------
        # Restore
        # -----------------------------
        - bash: |
            dotnet restore "$(SOLUTION_PATH)" --configfile "$(NUGET_CONFIG_PATH)"
          displayName: "Restore"

        # -----------------------------
        # Build
        # -----------------------------
        - bash: |
            dotnet build "$(SOLUTION_PATH)" \
              --configuration Release \
              --no-restore
          displayName: "Build"

        # -----------------------------
        # Test
        # -----------------------------
        - bash: |
            dotnet test "$(SOLUTION_PATH)" \
              --configuration Release \
              --no-build
          displayName: "Test"

        # -----------------------------
        # Pack
        # -----------------------------
        - bash: |
            dotnet pack "$(PROJECT_PATH)" \
              --configuration Release \
              --no-build \
              --output "$(Build.ArtifactStagingDirectory)/nupkg" \
              /p:PackageVersion=$(TAG)
          displayName: "Pack"

        # -----------------------------
        # Publish artifact
        # -----------------------------
        - publish: $(Build.ArtifactStagingDirectory)/nupkg
          artifact: nugetPackage
          displayName: "Upload NuGet artifact"

# ============================================================
# PUBLISH STAGE
# ============================================================
- stage: Publish
  displayName: "Publish to BaGet"
  dependsOn: Build
  condition: succeeded()

  jobs:
    - job: PublishJob
      pool:
        vmImage: ubuntu-latest

      steps:
        - download: current
          artifact: nugetPackage
          displayName: "Download NuGet package"

        - bash: |
            dotnet nuget push "$(Pipeline.Workspace)/nugetPackage/**/*.nupkg" \
              --api-key "$(GH_KAMIYOMU_GITEA_APIKEY)" \
              --source "$(GH_KAMIYOMU_GITEA_URL)" \
              --skip-duplicate
          displayName: "Push to BaGet"